name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Copy repository
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1.14.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 17
      - name: Install npm dependencies
        run: npm ci
      - name: build app
        run: npm run build
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
